# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: update bucket

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
permissions:
  contents: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: update bucket
      env: 
         GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python update.py bucket | tee /tmp/update_bucket.log
    - name: Commit and push if changed
      run: |
        git config --global user.email "test"
        git config --global user.name "test"
        git add .
        MESSAGE=$(cat /tmp/update_bucket.log)
        COMMIT_MESSAGE="$MESSAGE"
        git diff-index --quiet HEAD || git commit -m "$(echo -e "$COMMIT_MESSAGE")"
        git push
